[package]
name = "rust_first_steps"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
ndarray = "0.16.1"
ndarray-csv = "0.5.3"
ndarray-rand = "0.15.0"
plotly = "0.12.1"
rand = "0.9.1"
serde = "1.0.219"
